#!/usr/bin/env python3
"""Detect invalid UTF-8 or likely mojibake in distributable release text files."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
import zipfile
from pathlib import Path, PurePosixPath


TEXT_SUFFIXES = {".cfg", ".csv", ".htm", ".html", ".ini", ".json", ".md", ".txt", ".xml"}
TEXT_FILE_NAMES = {"NOTICE", "README", "LICENSE"}
TEXT_ROOTS = ("docs", "licenses")
ROOT_TEXT_FILES = {"manifest.json", "checksums.sha256", "pdf_workspace_setup.json"}


def is_checked_text_path(relative_path: str) -> bool:
    path = PurePosixPath(relative_path)
    if path.name in ROOT_TEXT_FILES:
        return True
    return path.parts and path.parts[0] in TEXT_ROOTS and (
        path.suffix.lower() in TEXT_SUFFIXES or path.name.upper() in TEXT_FILE_NAMES
    )


def requires_utf8(relative_path: str) -> bool:
    """Require UTF-8 only for documents authored or generated by this project.

    Vendored license originals may legally be supplied in legacy encodings and
    must be copied verbatim rather than rewritten merely to satisfy this gate.
    """
    path = PurePosixPath(relative_path)
    return path.name in ROOT_TEXT_FILES or path.parts[:1] == ("docs",) or relative_path == "licenses/README.txt"


def looks_like_mojibake(text: str) -> bool:
    """Catch text that can be reversibly repaired from Windows-1252 to UTF-8.

    This avoids treating ordinary Japanese, Latin-1, or emoji text as mojibake;
    a valid text has to form a different valid UTF-8 text after the reversal.
    """
    try:
        repaired = text.encode("cp1252").decode("utf-8")
    except UnicodeError:
        return False
    return repaired != text and any(ord(char) > 0x7F for char in repaired)


def validate_text_bytes(content: bytes, *, label: str, require_utf8: bool) -> list[str]:
    try:
        text = content.decode("utf-8-sig")
    except UnicodeDecodeError as error:
        return [f"invalid UTF-8: {label} ({error})"] if require_utf8 else []
    errors: list[str] = []
    if "\ufffd" in text:
        errors.append(f"replacement character indicates possible mojibake: {label}")
    if looks_like_mojibake(text):
        errors.append(f"likely Windows-1252/UTF-8 mojibake: {label}")
    return errors


def checked_directory_files(release_dir: Path) -> list[tuple[str, Path]]:
    return [
        (path.relative_to(release_dir).as_posix(), path)
        for path in release_dir.rglob("*")
        if path.is_file() and is_checked_text_path(path.relative_to(release_dir).as_posix())
    ]


def validate_release_directory(release_dir: Path) -> list[str]:
    if not release_dir.is_dir():
        return [f"release directory does not exist: {release_dir}"]
    errors: list[str] = []
    for relative_path, path in checked_directory_files(release_dir):
        errors.extend(validate_text_bytes(
            path.read_bytes(), label=relative_path, require_utf8=requires_utf8(relative_path)
        ))
    return errors


def validate_release_zip(release_dir: Path, zip_path: Path) -> list[str]:
    if not zip_path.is_file() or zip_path.stat().st_size == 0:
        return [f"release ZIP does not exist or is empty: {zip_path}"]
    errors: list[str] = []
    try:
        with zipfile.ZipFile(zip_path) as archive:
            names = set(archive.namelist())
            for relative_path, path in checked_directory_files(release_dir):
                member = PurePosixPath(release_dir.name, *PurePosixPath(relative_path).parts).as_posix()
                if member not in names:
                    errors.append(f"release ZIP is missing checked text file: {relative_path}")
                    continue
                archived = archive.read(member)
                if hashlib.sha256(archived).digest() != hashlib.sha256(path.read_bytes()).digest():
                    errors.append(f"release ZIP text file differs from unpacked release: {relative_path}")
                    continue
                errors.extend(validate_text_bytes(
                    archived, label=f"ZIP:{relative_path}", require_utf8=requires_utf8(relative_path)
                ))
    except zipfile.BadZipFile as error:
        errors.append(f"invalid release ZIP: {zip_path} ({error})")
    return errors


def child_path(root: Path, value: object, *, label: str) -> Path:
    if not isinstance(value, str) or not value:
        raise ValueError(f"release-set manifest is missing {label}")
    candidate = (root / value).resolve()
    if root.resolve() not in candidate.parents:
        raise ValueError(f"release-set manifest {label} escapes the release set: {value}")
    return candidate


def validate_release_set(release_set: Path) -> list[str]:
    manifest_path = release_set / "release_set_manifest.json"
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8-sig"))
        components = manifest["components"]
    except (OSError, UnicodeDecodeError, json.JSONDecodeError, KeyError, TypeError) as error:
        return [f"invalid release-set manifest: {manifest_path} ({error})"]
    errors: list[str] = []
    for label, directory_key, zip_key in (("full", "release", "release_zip"), ("Lite", "release_lite", "release_lite_zip")):
        try:
            release_dir = child_path(release_set, components.get(directory_key), label=f"{label} directory")
            zip_path = child_path(release_set, components.get(zip_key), label=f"{label} ZIP")
        except ValueError as error:
            errors.append(str(error))
            continue
        errors.extend(f"{label}: {error}" for error in validate_release_directory(release_dir))
        errors.extend(f"{label}: {error}" for error in validate_release_zip(release_dir, zip_path))
    return errors


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--release-set", type=Path, required=True)
    args = parser.parse_args(argv)
    errors = validate_release_set(args.release_set)
    if errors:
        print("Release text gate failed:", file=sys.stderr)
        for error in errors:
            print(f"- {error}", file=sys.stderr)
        return 1
    print(f"Release text gate passed: {args.release_set}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
