#!/usr/bin/env python3
"""Validate language catalogs and generate a compile-time C++ catalog."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


ID_RE = re.compile(r"^[a-z][a-z0-9]*(?:[._][a-z0-9]+)*$")
PLACEHOLDER_RE = re.compile(r"\{[A-Z][A-Z0-9_]*\}")


def load_catalog(path: Path) -> dict[str, str]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as error:
        raise ValueError(f"invalid catalog {path}: {error}") from error
    if not isinstance(value, dict):
        raise ValueError(f"catalog root must be an object: {path}")
    catalog: dict[str, str] = {}
    for key, text in value.items():
        if not isinstance(key, str) or not ID_RE.fullmatch(key):
            raise ValueError(f"invalid text ID in {path}: {key!r}")
        if not isinstance(text, str) or not text:
            raise ValueError(f"text for {key!r} must be a non-empty string: {path}")
        catalog[key] = text
    return catalog


def cpp_wide_literal(text: str) -> str:
    return 'L"' + text.replace("\\", "\\\\").replace('"', '\\"').replace("\r", "\\r").replace("\n", "\\n") + '"'


def generate_header(selected: dict[str, str]) -> str:
    lines = [
        "// Generated by tools/localization/generate_locale_catalog.py. Do not edit.",
        "#pragma once",
        "#include \"core/theme_types.h\"",
        "#include <string>",
        "#include <string_view>",
        "namespace generated_locale_catalog {",
        "inline std::wstring Text(std::wstring_view id) {",
    ]
    for key, value in sorted(selected.items()):
        lines.append(f"    if (id == {cpp_wide_literal(key)}) return {cpp_wide_literal(value)};")
    lines.extend(("    return std::wstring();", "}", "", "inline UiText BuildUiText() {", "    return UiText{"))
    ui_fields = (
        "appTitle menuFile menuView menuSave menuExport menuSearch menuOperation menuTemp menuHelp "
        "menuOpenWs menuReloadWs menuImportFile menuImportDirAsLecture menuImportDirAsSession "
        "menuOrganizeSessionFiles menuSaveAll menuSaveNote menuRecovery menuDeleteBackup menuExportPdf "
        "menuExportPdfPages menuExportPngPage menuExportNoteText menuExportNoteMarkup menuExportNoteHtml "
        "menuNewLecture btnNewLecture btnNewSession btnNewNote menuNewClro menuOpenWorkspaceDir "
        "menuOpenLectureDir menuOpenSessionDir menuExit menuResetZoom menuSetZoom menuFirstPage menuPrevPage menuNextPage "
        "menuLastPage menuJumpPage menuResetPdfPosition menuBottomPane menuBottomNote menuBottomHeadings "
        "menuBottomMath menuBottomAssist menuNoteWrap menuHelpGuide menuPdfInfo menuAbout menuCrash "
        "btnClearSel btnClearAnn btnToggleAnn btnModeSelect btnModePan btnModeMagnifier btnModeMarker "
        "btnModeMarkerFree btnModeText btnModeLine btnModeArrow btnModeWave btnModeFreehand btnModeShape "
        "btnModeEraser bottomReserved aboutTitle aboutText statusPageLabel statusZoomLabel errPdfOpen "
        "errNoteOpen errNoteSave errImportFile msgImportFileOverwrite errNewClroNoSession errNewClroCreate "
        "msgNewClroOk dlgNewLectureTitle dlgNewLectureLabel errLectureCreate errLectureExists "
        "dlgNewSessionTitle dlgNewSessionLabel errSessionCreate errSessionExists errSessionNoLecture "
        "menuSettings menuGeneralSettings menuNoteSettings menuMarkupSettings menuAnnotSettings "
        "menuSettingsPresetSave menuSettingsPresetLoad menuLectureSchedule menuAddTempExternalLecture "
        "menuRemoveTempExternalLecture menuTempOperation menuTempRestore menuTempDelete "
        "menuResetLectureLastOpen menuResetSessionLastOpen menuRestorePdfPosition menuRestoreLectureLastOpen "
        "menuRestoreSessionLastOpen menuDeletePdfPositionBackup menuDeleteLectureLastOpenBackup "
        "menuDeleteSessionLastOpenBackup menuRenamePdf menuRenameNote menuMovePdf menuMoveNote menuDiffManager "
        "menuOpenReadOnlyViewer menuLaunchReadOnlyViewer menuCloseAllReadOnlyViewers menuConvertOfficeToPdf "
        "menuCreateBlankPdf menuScrollDirection menuScrollDirVTopToBottom menuScrollDirVBottomToTop "
        "menuScrollDirHRightToLeft menuScrollDirHLeftToRight menuPdfSinglePageMode menuPaletteSettings"
    ).split()
    for field in ui_fields:
        text_id = "ui." + re.sub(r"(?<!^)([A-Z])", r"_\1", field).lower()
        lines.append(f"        Text({cpp_wide_literal(text_id)}),")
    lines.extend(("    };", "}", "}"))
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--locale", choices=("ja", "en"), required=True)
    parser.add_argument("--ja", type=Path, required=True)
    parser.add_argument("--localized", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--report", type=Path, required=True)
    args = parser.parse_args(argv)

    ja = load_catalog(args.ja)
    localized = load_catalog(args.localized)
    unknown = sorted(set(localized) - set(ja))
    if unknown:
        raise ValueError(f"{args.locale} catalog has IDs absent from Japanese catalog: {', '.join(unknown)}")
    for key, translated in localized.items():
        if set(PLACEHOLDER_RE.findall(translated)) != set(PLACEHOLDER_RE.findall(ja[key])):
            raise ValueError(f"placeholder mismatch for {key!r}")

    selected = ja if args.locale == "ja" else {key: localized.get(key, text) for key, text in ja.items()}
    fallback_ids = [] if args.locale == "ja" else sorted(set(ja) - set(localized))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generate_header(selected), encoding="utf-8", newline="\n")
    args.report.write_text(json.dumps({"locale": args.locale, "fallback_ids": fallback_ids}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8", newline="\n")
    print(json.dumps({"locale": args.locale, "fallback_count": len(fallback_ids)}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
