// file: core/theme_types.h
// テーマカラーとUIテキスト構造体。
// app_core.h から分離。<windows.h> と <string> のみに依存。
#pragma once

#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <windows.h>
#include <string>

struct ThemeColors {
    std::wstring name;
    std::wstring nameJp;
    COLORREF windowBg = RGB(255, 255, 255);
    COLORREF windowText = RGB(0, 0, 0);
    COLORREF panelBg = RGB(255, 255, 255);
    COLORREF panelText = RGB(0, 0, 0);
    COLORREF menuBg = RGB(245, 245, 245);
    COLORREF menuText = RGB(0, 0, 0);
    COLORREF menuSelBg = RGB(220, 235, 255);
    COLORREF menuSelText = RGB(0, 0, 0);
    COLORREF toolbarBg = RGB(245, 245, 245);
    COLORREF toolbarText = RGB(0, 0, 0);
    COLORREF buttonBg = RGB(250, 250, 250);
    COLORREF buttonText = RGB(0, 0, 0);
    COLORREF buttonBorder = RGB(180, 180, 180);
    COLORREF buttonHot = RGB(235, 245, 255);
    COLORREF buttonPressed = RGB(210, 230, 255);
    COLORREF splitterBg = RGB(235, 235, 235);
    COLORREF splitterLine = RGB(180, 180, 180);
    COLORREF pdfBg = RGB(200, 200, 200);
    COLORREF pdfPageBg = RGB(255, 255, 255);
    COLORREF noteBg = RGB(255, 255, 255);
    COLORREF noteText = RGB(0, 0, 0);
    COLORREF selectionBg = RGB(160, 210, 255);
    COLORREF selectionText = RGB(0, 0, 0);
    COLORREF accent = RGB(0, 120, 215);
};

struct UiText {
    std::wstring appTitle;
    std::wstring menuFile;
    std::wstring menuView;
    std::wstring menuSave;
    std::wstring menuExport;
    std::wstring menuSearch;
    std::wstring menuOperation;
    std::wstring menuTemp;
    std::wstring menuHelp;
    std::wstring menuOpenWs;
    std::wstring menuReloadWs;
    std::wstring menuImportFile;
    std::wstring menuImportDirAsLecture;
    std::wstring menuImportDirAsSession;
    std::wstring menuOrganizeSessionFiles;
    std::wstring menuSaveAll;
    std::wstring menuSaveNote;
    std::wstring menuRecovery;
    std::wstring menuDeleteBackup;
    std::wstring menuExportPdf;
    std::wstring menuExportPdfPages;
    std::wstring menuExportPngPage;
    std::wstring menuExportNoteText;
    std::wstring menuExportNoteMarkup;
    std::wstring menuExportNoteHtml;
    std::wstring menuNewLecture;
    std::wstring btnNewLecture;
    std::wstring btnNewSession;
    std::wstring btnNewNote;
    std::wstring menuNewClro;
    std::wstring menuOpenWorkspaceDir;
    std::wstring menuOpenLectureDir;
    std::wstring menuExit;
    std::wstring menuResetZoom;
    std::wstring menuSetZoom;
    std::wstring menuFirstPage;
    std::wstring menuPrevPage;
    std::wstring menuNextPage;
    std::wstring menuLastPage;
    std::wstring menuJumpPage;
    std::wstring menuResetPdfPosition;
    std::wstring menuBottomPane;
    std::wstring menuBottomNote;
    std::wstring menuBottomHeadings;
    std::wstring menuBottomMath;
    std::wstring menuBottomAssist;
    std::wstring menuNoteWrap;
    std::wstring menuHelpGuide;
    std::wstring menuPdfInfo;
    std::wstring menuAbout;
    std::wstring menuCrash;
    std::wstring btnClearSel;
    std::wstring btnClearAnn;
    std::wstring btnToggleAnn;
    std::wstring btnModeSelect;
    std::wstring btnModePan;
    std::wstring btnModeMagnifier;
    std::wstring btnModeMarker;
    std::wstring btnModeMarkerFree;
    std::wstring btnModeText;
    std::wstring btnModeLine;
    std::wstring btnModeArrow;
    std::wstring btnModeWave;
    std::wstring btnModeFreehand;
    std::wstring btnModeShape;
    std::wstring btnModeEraser;
    std::wstring bottomReserved;
    std::wstring aboutTitle;
    std::wstring aboutText;
    std::wstring statusPageLabel;
    std::wstring statusZoomLabel;
    std::wstring errPdfOpen;
    std::wstring errNoteOpen;
    std::wstring errNoteSave;
    std::wstring errImportFile;
    std::wstring msgImportFileOverwrite;
    std::wstring errNewClroNoSession;
    std::wstring errNewClroCreate;
    std::wstring msgNewClroOk;
    std::wstring dlgNewLectureTitle;
    std::wstring dlgNewLectureLabel;
    std::wstring errLectureCreate;
    std::wstring errLectureExists;
    std::wstring dlgNewSessionTitle;
    std::wstring dlgNewSessionLabel;
    std::wstring errSessionCreate;
    std::wstring errSessionExists;
    std::wstring errSessionNoLecture;
    std::wstring menuSettings;
    std::wstring menuGeneralSettings;
    std::wstring menuNoteSettings;
    std::wstring menuMarkupSettings;
    std::wstring menuAnnotSettings;
    std::wstring menuSettingsPresetSave;
    std::wstring menuSettingsPresetLoad;
    std::wstring menuLectureSchedule;
    std::wstring menuAddTempExternalLecture;
    std::wstring menuRemoveTempExternalLecture;
    std::wstring menuTempOperation;
    std::wstring menuTempRestore;
    std::wstring menuTempDelete;
    std::wstring menuResetLectureLastOpen;
    std::wstring menuResetSessionLastOpen;
    std::wstring menuRestorePdfPosition;
    std::wstring menuRestoreLectureLastOpen;
    std::wstring menuRestoreSessionLastOpen;
    std::wstring menuDeletePdfPositionBackup;
    std::wstring menuDeleteLectureLastOpenBackup;
    std::wstring menuDeleteSessionLastOpenBackup;
    std::wstring menuRenamePdf;
    std::wstring menuRenameNote;
    std::wstring menuMovePdf;
    std::wstring menuMoveNote;
    std::wstring menuDiffManager;
    std::wstring menuOpenReadOnlyViewer;
    std::wstring menuLaunchReadOnlyViewer;
    std::wstring menuCloseAllReadOnlyViewers;
    std::wstring menuConvertOfficeToPdf;
    std::wstring menuCreateBlankPdf;

    std::wstring menuScrollDirection;
    std::wstring menuScrollDirVTopToBottom;
    std::wstring menuScrollDirVBottomToTop;
    std::wstring menuScrollDirHRightToLeft;
    std::wstring menuScrollDirHLeftToRight;
    std::wstring menuPdfSinglePageMode;
    std::wstring menuPaletteSettings;
};
